version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - '8000:80' # Host Port:Container Port
    volumes:
      - ./backend/src:/var/www/html
    depends_on:
      - db


  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db_data:
